; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; this config is inspired by this GitHub comment for getting Arduino working on the ESP32-C6:
; https://github.com/espressif/arduino-esp32/issues/10743#issuecomment-2548663001
[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
framework = arduino
lib_deps =
	adafruit/Adafruit SH110X@^2.1.13
	adafruit/Adafruit BusIO@^1.17.1
	adafruit/Adafruit GFX Library@^1.12.1
	adafruit/Adafruit seesaw Library@^1.7.9
	gilmaimon/ArduinoWebsockets@^0.5.4
	bblanchon/ArduinoJson@^7.0.4
	https://github.com/ky1ejs/rotary-encoder-esp32.git
monitor_speed = 115200
monitor_filters = direct
build_flags = 
	-D CORE_DEBUG_LEVEL=3
	-D ARDUINO_USB_MODE=1
	-D CONFIG_ZB_ENABLED=1
	-D ARDUINO_USB_CDC_ON_BOOT=1

[env:esp32-c6-devkitc-1]
board = esp32-c6-devkitc-1
build_flags = 
	; Custom I2C pin definitions for this board
	-D BOARD_SDA=6
	-D BOARD_SCL=7
	; WebSocket configuration - disable SSL for local connections
	-D WEBSOCKETS_NETWORK_TYPE=NETWORK_ESP32

[env:adafruit_feather_esp32c6]
board = adafruit_feather_esp32c6
	; Custom I2C pin definitions for this board
	-D BOARD_SDA=6
	-D BOARD_SCL=7
	; WebSocket configuration - disable SSL for local connections
	-D WEBSOCKETS_NETWORK_TYPE=NETWORK_ESP32
